Vagrant.configure(2) do |config|
  config.vm.box = "juniper/ffp-12.1X47-D15.4-packetmode"

  #config.vm.provision "ansible" do |ansible|
    #ansible.playbook = "ansible_playbook.yml"
  #end

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
    vb.cpus = 2
  end

  config.vm.define "vsrxp1" do |vsrxp1|
    vsrxp1.vm.host_name = "vsrxp1"
    vsrxp1.vm.network "private_network",
                      virtualbox__intnet: "l1"
    vsrxp1.vm.network "private_network",
                      virtualbox__intnet: "l2"
    vsrxp1.vm.network "private_network",
                      virtualbox__intnet: "l3"
  end
  config.vm.define "vsrxp2" do |vsrxp2|
    vsrxp2.vm.host_name = "vsrxp2"
    vsrxp2.vm.network "private_network",
                      virtualbox__intnet: "l1"
    vsrxp2.vm.network "private_network",
                      virtualbox__intnet: "l2"
    vsrxp2.vm.network "private_network",
                      virtualbox__intnet: "l3"
  end
end
